modLoader="javafml"
loaderVersion="[35,)"
license="BSD-3-Clause"

[[mods]]
modId="voteme"
version="${file.jarVersion}"
displayName="VoteMe"
authors="TeaConMC"
description="Minecraft mod for in-game voting"

[[dependencies.voteme]]
modId="forge"
mandatory=true
versionRange="[35.1.0,)"
ordering="NONE"
side="BOTH"
