modLoader="javafml"
loaderVersion="[4,)"
license="BSD-3-Clause"

[[mods]]
modId="voteme"
version="${mod_version}"
displayName="Vote Me"
authors="TeaConMC, yuriscat (Yuri's Cat), 3TUSK, ustc-zzzz"
description="Minecraft mod for in-game voting."

[[dependencies.voteme]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.voteme]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.2)"
ordering="NONE"
side="BOTH"

